---
# Worker
PrivateKeys.ca_key: "%(%(CA_PRIVATE_KEY_PATH|env)|file)"
CA.certificate: "%(%(CA_CERT_PATH|env)|file)"

# Database
Database.implementation: MysqlDB
Mysql.host: "%(MYSQL_HOST|env)"
Mysql.port: "%(MYSQL_PORT|env)"
Mysql.database: "%(MYSQL_DATABASE_NAME|env)"
Mysql.username: "%(MYSQL_DATABASE_USERNAME|env)"
Mysql.password: "%(MYSQL_DATABASE_PASSWORD|env)"

# We initialize via config file and not grr_config_updater
Server.initialized: True

# Health Checking
Monitoring.http_port: "%(MONITORING_HTTP_PORT|env)"

# Logging
Logging.path: /var/log/grr/
Logging.verbose: True
